apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /api/agendamento
        backend:
          serviceName: agendamento
          servicePort: 80
      - path: /api/pagamento
        backend:
          serviceName: pagamento
          servicePort: 80
      - path: /api/checkin
        backend:
          serviceName: checkin
          servicePort: 80
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
          