apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      hostname: pubsub
      subdomain: redis
      containers:
      - name: redis
        image: redis:4
        args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
        tty: true
        stdin: true
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-volume
      volumes:
      - name: redis-volume
        emptyDir: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
        