apiVersion: v1
kind: Service
metadata:
  name: rediscadagenbraga
spec:
  selector:
    name: rediscadagenbraga
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscadagenbraga
  labels:
    name: rediscadagenbraga
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rediscadagenbraga
  template:
    metadata:
      labels:
        app: rediscadagenbraga
        name: rediscadagenbraga
    spec:
      hostname: cadagenbraga
      subdomain: rediscadagenbraga
      containers:
      - name: rediscadagenbraga
        image: redis:4
        args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
        tty: true
        stdin: true
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data/rediscadagenbraga
          name: rediscadagenbraga-volume
      volumes:
      - name: rediscadagenbraga-volume
        emptyDir: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rediscadagenbraga-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rediscadagenbraga"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rediscadagenbraga-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
        