apiVersion: v1
kind: Service
metadata:
  name: rediscadpag
spec:
  selector:
    name: rediscadpag
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscadpag
  labels:
    name: rediscadpag
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rediscadpag
  template:
    metadata:
      labels:
        app: rediscadpag
        name: rediscadpag
    spec:
      hostname: cadpag
      subdomain: rediscadpag
      containers:
      - name: rediscadpag
        image: redis:4
        args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
        tty: true
        stdin: true
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data/rediscadpag
          name: rediscadpag-volume
      volumes:
      - name: rediscadpag-volume
        emptyDir: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rediscadpag-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rediscadpag"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rediscadpag-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
        