apiVersion: v1
kind: Service
metadata:
  name: rediscadagen
spec:
  selector:
    name: rediscadagen
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscadagen
  labels:
    name: rediscadagen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rediscadagen
  template:
    metadata:
      labels:
        app: rediscadagen
        name: rediscadagen
    spec:
      hostname: cadagen
      subdomain: rediscadagen
      containers:
      - name: rediscadagen
        image: redis:4
        args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
        tty: true
        stdin: true
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data/rediscadagen
          name: rediscadagen-volume
      volumes:
      - name: rediscadagen-volume
        emptyDir: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rediscadagen-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rediscadagen"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rediscadagen-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
        