---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: agendamentobraga
  name: agendamentobraga
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: agendamentobraga
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: agendamentobraga
    spec:
      containers:
      - image: micro-agendamento:v1
        imagePullPolicy: IfNotPresent
        name: agendamentobraga
        env:
          - name: BD_URL
            value: mongodb+srv://testemongodb:modbMAdTU3sjEqns@cluster0-pmvdk.mongodb.net/test?retryWrites=true&w=majority
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: agendamentobraga
  name: agendamentobraga
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  agendamentobraga_mapping
      prefix: /agendamento/braga/
      rewrite: /api/agendamento/
      service: agendamentobraga
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: agendamentobraga
  sessionAffinity: None
  type: ClusterIP