---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pagamentoporto
  name: pagamentoporto
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pagamentoporto
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: pagamentoporto
    spec:
      containers:
      - image: micro-pagamento:v1
        imagePullPolicy: IfNotPresent
        name: pagamentoporto
        ports:
        - containerPort: 30123
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pagamentoporto
  name: pagamentoporto
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  agendamentoporto_mapping
      prefix: /pagamento/porto/
      rewrite: /api/pagamento/
      service: pagamentoporto
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30123
  selector:
    run: pagamentoporto
  sessionAffinity: None
  type: ClusterIP